# .gitlab


include:
#  - template: 'Jobs/Code-Quality.gitlab-ci.yml'
  - template: 'Jobs/SAST.gitlab-ci.yml'
stages:
  - build
  - test
  - dev-deploy
  - secure

variables:
  DOCKER_IMAGE_PREFIX: "netflix-app"
  DOCKER_REGISTRY_URL: "registry.local:8443"
  PORT: 8080
  DOCKER_DRIVER: overlay2
  SCAN_KUBERNETES_MANIFESTS: "true"

sast:
  stage: .pre
